<?php
defined('ABSPATH') || exit;
function gopa_collection($atts){
    $a=shortcode_atts(['type'=>'gopa_field','limit'=>6,'paginate'=>'no'],$atts);
    $allowed=['gopa_field','gopa_course','gopa_event','gopa_resource','gopa_hub','post'];if(!in_array($a['type'],$allowed,true))return '';
    $key='gopa_page_'.$a['type'];$paged=$a['paginate']==='yes'?max(1,absint($_GET[$key]??1)):1;
    $args=['post_type'=>$a['type'],'posts_per_page'=>min(24,max(1,(int)$a['limit'])),'paged'=>$paged,'orderby'=>$a['type']==='post'?'date':'menu_order','order'=>$a['type']==='post'?'DESC':'ASC'];
    $category=sanitize_title(wp_unslash($_GET['gopa_resource_category']??''));
    if($a['type']==='gopa_resource'&&$category)$args['tax_query']=[['taxonomy'=>'gopa_resource_type','field'=>'slug','terms'=>$category]];
    $q=new WP_Query($args);
    ob_start();if($q->have_posts()): ?><div id="<?php echo esc_attr('collection-'.$a['type']); ?>" class="collection-grid <?php echo esc_attr($a['type']); ?>"><?php while($q->have_posts()):$q->the_post();$terms=wp_get_object_terms(get_the_ID(),'gopa_resource_type',['fields'=>'slugs']); ?>
    <article class="content-card reveal" data-resource-terms="<?php echo esc_attr(is_wp_error($terms)?'':implode(' ',$terms)); ?>"><a href="<?php the_permalink(); ?>" class="card-link"><?php if(has_post_thumbnail()): ?><div class="card-image"><?php the_post_thumbnail('large',['loading'=>'lazy']); ?></div><?php endif; ?><div class="card-body"><span class="eyebrow"><?php $date=get_post_meta(get_the_ID(),'gopa_date',true);echo esc_html($date?date_i18n(get_option('date_format'),strtotime($date)):(get_post_meta(get_the_ID(),'gopa_label',true)?:gopa_text('card_label'))); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_the_excerpt()); ?></p><span class="card-bottom"><?php echo esc_html(get_post_meta(get_the_ID(),'gopa_button',true)?:gopa_text('card_action')); ?> <?php echo gopa_arrow(); ?></span></div></a></article>
    <?php endwhile; ?></div><?php if($a['paginate']==='yes'&&$q->max_num_pages>1){$base=esc_url_raw(add_query_arg($key,999999999));echo '<nav class="collection-pagination" aria-label="'.esc_attr(gopa_text('nav_label')).'">'.wp_kses_post(paginate_links(['base'=>str_replace('999999999','%#%',$base),'format'=>'','total'=>$q->max_num_pages,'current'=>$paged,'prev_text'=>gopa_text('previous_label'),'next_text'=>gopa_text('next_label'),'add_fragment'=>'#collection-'.$a['type']])).'</nav>';}else{} ?>
    <?php else: ?><p class="empty-state"><?php echo esc_html(gopa_text($a['type']==='gopa_hub'?'hub_empty':'empty_collection')); ?></p><?php endif;wp_reset_postdata();return ob_get_clean();
}
add_shortcode('gopa_collection','gopa_collection');
add_shortcode('gopa_resource_filters',function(){ $terms=get_terms(['taxonomy'=>'gopa_resource_type','hide_empty'=>true]);if(is_wp_error($terms)||!$terms)return ''; $current=sanitize_title(wp_unslash($_GET['gopa_resource_category']??''));$out='<form class="resource-filter" method="get" action="'.esc_url(get_permalink().'#collection-gopa_resource').'" aria-label="'.esc_attr(gopa_text('filter_label')).'"><button type="submit" name="gopa_resource_category" value="" aria-pressed="'.($current===''?'true':'false').'">'.esc_html(gopa_text('all_resources')).'</button>';foreach($terms as $term)$out.='<button type="submit" name="gopa_resource_category" value="'.esc_attr($term->slug).'" aria-pressed="'.($current===$term->slug?'true':'false').'">'.esc_html($term->name).'</button>';return $out.'</form>';});
add_shortcode('gopa_giving_link',function(){ $url=gopa_setting('donate_url');return $url?'<p><a class="button" href="'.esc_url($url).'">'.esc_html(gopa_text('giving_label')).' ↗</a></p>':''; });
add_shortcode('gopa_media_links',function(){ $out='';foreach(['podcast_url'=>'podcast_label','livestream_url'=>'livestream_label','donate_url'=>'giving_label'] as $key=>$label){$url=gopa_setting($key);if($url)$out.='<a class="button" href="'.esc_url($url).'">'.esc_html(gopa_text($label)).' ↗</a> ';}return $out?'<p class="media-links">'.$out.'</p>':'<p>'.esc_html(gopa_text('media_empty')).'</p>';});
function gopa_social_links($empty=false){$out='';foreach(['facebook','instagram','youtube','tiktok','x','linkedin'] as $key){if(gopa_setting($key))$out.='<a href="'.esc_url(gopa_setting($key)).'">'.esc_html(gopa_text($key.'_label')).' ↗</a>';}return $out?'<div class="social-links">'.$out.'</div>':($empty?'<p>'.esc_html(gopa_text('social_empty')).'</p>':'');}
add_shortcode('gopa_social_links',function(){return gopa_social_links(true);});
add_shortcode('gopa_contact',function($atts){
    $a=shortcode_atts(['interest'=>''],$atts);$options=gopa_interests();$selected=$a['interest']?:sanitize_text_field(wp_unslash($_GET['interest']??''));
    ob_start();$status=isset($_GET['enquiry'])?sanitize_key(wp_unslash($_GET['enquiry'])):''; ?>
<div class="contact-layout"><div><span class="eyebrow"><?php echo esc_html(gopa_text('contact_eyebrow')); ?></span><h2><?php echo esc_html(gopa_setting('contact_heading','There’s a place for you here.')); ?></h2><p><?php echo esc_html(gopa_setting('contact_description','Connect with the movement. Tell us how you’d like to get involved.')); ?></p><a class="text-link" href="mailto:<?php echo esc_attr(gopa_setting('email','info@gospelpanthers.com')); ?>"><?php echo esc_html(gopa_setting('email','info@gospelpanthers.com')); ?> ↗</a></div>
<form class="enquiry-form" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" method="post"><input type="hidden" name="action" value="gopa_enquiry"><?php wp_nonce_field('gopa_enquiry','gopa_nonce'); ?>
<?php if($status): ?><p role="status" class="form-status"><?php echo esc_html(gopa_text($status==='received'?'form_success':'form_error')); ?></p><?php endif; ?>
<div class="form-row"><label><?php echo esc_html(gopa_text('form_name')); ?><input name="person" autocomplete="name" maxlength="150" required></label><label><?php echo esc_html(gopa_text('form_email')); ?><input name="email" type="email" autocomplete="email" maxlength="200" required></label></div><label><?php echo esc_html(gopa_text('form_interest')); ?><select name="interest"><?php foreach($options as $option): ?><option <?php selected($selected,$option); ?>><?php echo esc_html($option); ?></option><?php endforeach; ?></select></label><label><?php echo esc_html(gopa_text('form_message')); ?><textarea name="message" rows="5" maxlength="5000" required></textarea></label><div class="honey" aria-hidden="true"><label>Leave this blank<input name="website" tabindex="-1" autocomplete="off"></label></div><label class="consent"><input type="checkbox" name="consent" value="1" required> <?php echo esc_html(gopa_text('form_consent')); ?> <a href="<?php echo esc_url(gopa_setting('privacy_url')?:gopa_url('privacy-policy')); ?>"><?php echo esc_html(gopa_text('privacy_label')); ?></a></label><button class="button" type="submit"><?php echo esc_html(gopa_text('form_submit')); ?> <?php echo gopa_arrow(); ?></button></form></div>
<?php return ob_get_clean(); });
